### ISSUE TITLE
Add links to Software Carpentry lessons and other resources for learning

### ISSUE THREAD

**Issue by santisoler** [fatiando/website#20]
**Description of the desired feature**

Would be nice to include links to resources on how to learn Python so new users that haven't so much experience with the language can start using Fatiando tools in the short term. We know there is a very large number of Python courses and tutorials, but most of them might not be the best options for the things they will do with Fatiando. In contrast, the [Software Carpentry](https://software-carpentry.org/) lessons have proved to be really great for starting to learn Python for scientific computation.

We can also mention other useful lessons from Software Carpentry, which may serve to anyone wanting to start contributing to the project, like the Unix Shell and Version Control with Git lessons.

We could add these lines on a new section called _Getting started_ located after _The Tools_, which can also provide links to Anaconda as our recommended Python distribution and instruct users to read the documentation of each package.
Maybe we also want to include links to the Transform2020 tutorial on Verde.

Probably, the links to the Python lessons could be on _Getting started_, while the links to the Bash and Git lessons could live inside _Getting Involved_.

I'm willing to hear more ideas about this!
The whole intention of this is to lower the barrier for newcomers that might feel overwhelmed of having to learn a new programming language, how to install it on their system, where to learn, etc.

**Are you willing to help implement and maintain this feature?** @aguspesce  told me she would be interested in tackling this down.

**Comment by aguspesce** [comment]
@santisoler, I like your idea... 
In the new section "_Getting started_", we can say that "Fatiando user" need to know something about Python and add the Software Carpentry lessons. 
We also recommend using the Anaconda Python distribution to use Fatiando and add the installation links created for Transform2020.

I think that the links to Git and Brash lessons could live inside _Getting Involved_.

What do you think?
I can start a draft with these ideas...

**Comment by leouieda** [comment]
100% agree with this!

> We could add these lines on a new section called Getting started located after The Tools, which can also provide links to Anaconda as our recommended Python distribution and instruct users to read the documentation of each package.
> In the new section "Getting started", we can say that "Fatiando user" need to know something about Python and add the Software Carpentry lessons.
> We also recommend using the Anaconda Python distribution to use Fatiando and add the installation links created for Transform2020.

Here is a proposal for the Getting Started section:

* First say that the Fatiando tools require Python. Link to Anaconda download (the the SWC instructions for this)
* Add a note for "New to Python?" with links to resources for learning (mostly the 2 SWC lessons on Python).
* Include instructions for install all of the latest tools with conda and pip with a single command (`conda install verde harmonica ...`)

> I think that the links to Git and Brash lessons could live inside Getting Involved.

Yes! That is brilliant and I don't know we haven't linked to those lessons before. 
But it might be best to add them to the [Contributing Guide](https://github.com/fatiando/contributing/blob/master/CONTRIBUTING.md#contributing-code) instead. 
What do you think?

>  Maybe we also want to include links to the Transform2020 tutorial on Verde.

This should definitely be in the Verde docs. Maybe in the front page or in Overview? 
I feel like it would be a bit out of place in the main fatiando page but I'm open to it.

>  I can start a draft with these ideas...

That would be amazing! Maybe we can run it by Andrea and Geolatinas once you have a draft to see what they think?

**Comment by leouieda** [comment]
Actually, about the Transform tutorial: We could definitely add something about that on Getting Started but maybe link to this playlist instead: https://www.youtube.com/playlist?list=PLPA_RM8wsOqJVm8SRdxwnrsMTut_GAV7F I'm gathering any fatiando related tutorials in there.

**Comment by aguspesce** [comment]
Ok! I will start a draft.... When I have something interesting, I will show it to Andrea and Geolatinas

**Comment by aguspesce** [comment]
Hello @santisoler ans @leouieda, 
I improve the website... I add the "Getting Started" section. What do you think?  

>  >I think that the links to Git and Brash lessons could live inside Getting Involved.

> Yes! That is brilliant and I don't know we haven't linked to those lessons before.
> But it might be best to add them to the Contributing Guide instead.
> What do you think?

I think that you are right about this.

> > Maybe we also want to include links to the Transform2020 tutorial on Verde.

> This should definitely be in the Verde docs. Maybe in the front page or in Overview?
> I feel like it would be a bit out of place in the main fatiando page but I'm open to it.

I think the same as you
