### ISSUE TITLE
Add links to Verde, Harmonica, Boule, Ensaio to front page visible without scrolling

### ISSUE THREAD

**Issue by craigmillernz** [fatiando/website#62]
The first screen of the Fatiando home page fits so well in the browser that it's not obvious there is much more below it accessible when scrolling down.  This makes links to the Fatiando packages at the lower part of the page not obvious.  Adding shortcuts on the first part of the home page, to the Verde, Harmonica etc content lower down  (or directly to the main sites) would make these packages more visible without needing to scroll down.

Possible solution sketched below.

![image](https://user-images.githubusercontent.com/5473482/184712786-db417471-921d-48ab-8246-f7e66df586b3.png)

**Comment by leouieda** [comment]
@craigmillernz should be fixed in #64. Could you please take a look at https://www.fatiando.org to see if this solves the issue you spotted? Feel free to reopen this issue if it doesn't or needs improvement.

**Comment by craigmillernz** [comment]
Looks great!! Thanks for updating that quickly.
